# **Handling missing values**

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/synthetic_dataset.csv')
np.random.seed(0)
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [5]:
# missing value count
missing_values_count = df.isnull().sum()
print(missing_values_count)

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

In [9]:
# % of missing values
total_cells = np.prod(df.shape)
empty_cells = missing_values_count.sum()

missing_value_percentage = (empty_cells/total_cells) * 100

print(missing_value_percentage)

30.793214121962404

In [34]:
# use df.dropna()if you want to delete missing values.

delete_rows_with_missing_values = df.dropna()
# dlt_category = df.drop(columns=['Category'], inplace=True)
print(delete_rows_with_missing_values)
delete_rows_with_missing_values.head()

       Price    Rating         Stock  Discount
6      667.0  3.668341      In Stock      41.0
7     7125.0  4.983998  Out of Stock       7.0
8     2777.0  2.678384      In Stock       6.0
11    3772.0  4.890750      In Stock      45.0
12    7719.0  2.982242      In Stock       4.0
...      ...       ...           ...       ...
4339  6807.0  4.195968      In Stock       9.0
4342  9847.0  3.667649  Out of Stock      49.0
4343   843.0  2.752754  Out of Stock      48.0
4350  8030.0  4.391910  Out of Stock      20.0
4352  8230.0  2.410736  Out of Stock      29.0

[1398 rows x 4 columns]

     Price    Rating         Stock  Discount
6    667.0  3.668341      In Stock      41.0
7   7125.0  4.983998  Out of Stock       7.0
8   2777.0  2.678384      In Stock       6.0
11  3772.0  4.890750      In Stock      45.0
12  7719.0  2.982242      In Stock       4.0

In [15]:
print('Original No of Rows \n', df.shape[0])
print('No of Rows after Deleting Rows having Missing Values \n', delete_columns_with_missing_values.shape[0])

Original No of Rows
 4362
No of Rows after Deleting Rows having Missing Values
 540

if we want to make subset by column we will use df.loc[:, 1st column name: 2nd column name]
':' This colon means select all rows.
'1st column name: 2nd column name' This means select from 1st column to 2nd column.

In [41]:
# Creating a sub set to make it easy to view data.
df_subset = df.loc[0:20, :]
df_subset

     Price    Rating         Stock  Discount
0   5548.0  1.870322           NaN       0.0
1   3045.0  4.757798           NaN      38.0
2   4004.0       NaN      In Stock       0.0
3   4808.0  1.492085           NaN      33.0
4   1817.0       NaN  Out of Stock      23.0
5   3522.0       NaN           NaN       NaN
6    667.0  3.668341      In Stock      41.0
7   7125.0  4.983998  Out of Stock       7.0
8   2777.0  2.678384      In Stock       6.0
9    463.0  4.626187           NaN       3.0
10  1151.0  2.947838           NaN       NaN
11  3772.0  4.890750      In Stock      45.0
12  7719.0  2.982242      In Stock       4.0
13  8416.0  1.270943           NaN      29.0
14  8530.0       NaN           NaN      10.0
15  7936.0  3.032832      In Stock      44.0
16  9319.0  3.479064      In Stock      28.0
17     NaN  4.097464           NaN      40.0
18  2066.0       NaN           NaN      30.0
19  1784.0       NaN           NaN      12.0
20  5589.0       NaN           NaN      39.0

In [37]:
# filling the missing value
df.fillna(0)

       Price    Rating         Stock  Discount
0     5548.0  1.870322             0       0.0
1     3045.0  4.757798             0      38.0
2     4004.0  0.000000      In Stock       0.0
3     4808.0  1.492085             0      33.0
4     1817.0  0.000000  Out of Stock      23.0
...      ...       ...           ...       ...
4357  4436.0  4.728335             0      49.0
4358  6236.0  0.000000  Out of Stock       4.0
4359  3283.0  0.000000  Out of Stock       9.0
4360  2999.0  4.425995             0      40.0
4361     0.0  2.184471             0       0.0

[4362 rows x 4 columns]

In [40]:
# backward filling
df.fillna(method='bfill', axis=0).fillna(0)

/tmp/ipykernel_1048/936259153.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', axis=0).fillna(0)

       Price    Rating         Stock  Discount
0     5548.0  1.870322      In Stock       0.0
1     3045.0  4.757798      In Stock      38.0
2     4004.0  1.492085      In Stock       0.0
3     4808.0  1.492085  Out of Stock      33.0
4     1817.0  3.668341  Out of Stock      23.0
...      ...       ...           ...       ...
4357  4436.0  4.728335  Out of Stock      49.0
4358  6236.0  4.425995  Out of Stock       4.0
4359  3283.0  4.425995  Out of Stock       9.0
4360  2999.0  4.425995             0      40.0
4361     0.0  2.184471             0       0.0

[4362 rows x 4 columns]