In [1]:
# importing pandas and numpy libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [2]:
# loading csv file
district_prices = pd.read_csv('/content/District-prices-monthly.csv')
district_prices.head()

,year_month,district,okrug,secondary_price_per_sqm,newbuild_price_per_sqm,rental_price_per_sqm_monthly,secondary_mom_change_pct,newbuild_mom_change_pct,n_listings_secondary,n_listings_newbuild,n_listings_rental,cbr_key_rate_pct,avg_mortgage_rate_pct
0,2020-01,Arbat,CAO,480000,543700,2000,NaN,NaN,104,68,41,6.00,8.50
1,2020-02,Arbat,CAO,469100,531500,1955,-2.28,-2.24,22,63,50,6.00,8.50
2,2020-03,Arbat,CAO,502200,559800,2093,7.07,5.33,104,56,28,6.00,8.50
3,2020-04,Arbat,CAO,505100,541500,2104,0.56,-3.27,168,29,107,4.25,6.75
4,2020-05,Arbat,CAO,523500,594800,2181,3.65,9.84,66,58,57,4.25,6.75

In [3]:
# displaying column names
district_prices.columns.tolist()

['year_month',
 'district',
 'okrug',
 'secondary_price_per_sqm',
 'newbuild_price_per_sqm',
 'rental_price_per_sqm_monthly',
 'secondary_mom_change_pct',
 'newbuild_mom_change_pct',
 'n_listings_secondary',
 'n_listings_newbuild',
 'n_listings_rental',
 'cbr_key_rate_pct',
 'avg_mortgage_rate_pct']

In [4]:
# standarizing column names by replacing - and capatalizing all letters
district_prices.columns = district_prices.columns.str.replace('_', ' ')
district_prices.columns = district_prices.columns.str.upper()

In [5]:
# displaying columns names after applying changes
district_prices.columns.tolist()

['YEAR MONTH',
 'DISTRICT',
 'OKRUG',
 'SECONDARY PRICE PER SQM',
 'NEWBUILD PRICE PER SQM',
 'RENTAL PRICE PER SQM MONTHLY',
 'SECONDARY MOM CHANGE PCT',
 'NEWBUILD MOM CHANGE PCT',
 'N LISTINGS SECONDARY',
 'N LISTINGS NEWBUILD',
 'N LISTINGS RENTAL',
 'CBR KEY RATE PCT',
 'AVG MORTGAGE RATE PCT']

In [6]:
# checking for duplicated values
district_prices.duplicated().sum()

np.int64(0)

In [7]:
# checking for information about columns. which show us datatypes of columns and number of non null values
district_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9804 entries, 0 to 9803
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   YEAR MONTH                    9804 non-null   object
 1   DISTRICT                      9804 non-null   object
 2   OKRUG                         9804 non-null   object
 3   SECONDARY PRICE PER SQM       9804 non-null   int64
 4   NEWBUILD PRICE PER SQM        9804 non-null   int64
 5   RENTAL PRICE PER SQM MONTHLY  9804 non-null   int64
 6   SECONDARY MOM CHANGE PCT      9675 non-null   float64
 7   NEWBUILD MOM CHANGE PCT       9675 non-null   float64
 8   N LISTINGS SECONDARY          9804 non-null   int64
 9   N LISTINGS NEWBUILD           9804 non-null   int64
 10  N LISTINGS RENTAL             9804 non-null   int64
 11  CBR KEY RATE PCT              9804 non-null   float64
 12  AVG MORTGAGE RATE PCT         9804 non-null   float64
dtypes: float64(4), int64(6), object(3)
memory usage: 995.8+ KB

In [8]:
# we will check missing values
district_prices.isnull().sum()

YEAR MONTH                        0
DISTRICT                          0
OKRUG                             0
SECONDARY PRICE PER SQM           0
NEWBUILD PRICE PER SQM            0
RENTAL PRICE PER SQM MONTHLY      0
SECONDARY MOM CHANGE PCT        129
NEWBUILD MOM CHANGE PCT         129
N LISTINGS SECONDARY              0
N LISTINGS NEWBUILD               0
N LISTINGS RENTAL                 0
CBR KEY RATE PCT                  0
AVG MORTGAGE RATE PCT             0
dtype: int64

As you can see only 2 columns have missing values. We will deal with them when cleaning that particular column. Now we will start with 1st column and then move to next one by one.

In [9]:
# changing the datatype of 1st column to datetime as the column is representing date
district_prices['YEAR MONTH'] = pd.to_datetime(district_prices['YEAR MONTH'], errors='coerce')

In [10]:
print(district_prices['YEAR MONTH'].dtype)

datetime64[ns]

In [11]:
# changing the name of column from YEAR MONTH TO DATE
district_prices.rename(columns= {'YEAR MONTH': 'DATE'}, inplace= True)

In [15]:
# moving to next column
print(district_prices['DISTRICT'])

0               Arbat
1               Arbat
2               Arbat
3               Arbat
4               Arbat
            ...
9799    Shchapovskoye
9800    Shchapovskoye
9801    Shchapovskoye
9802    Shchapovskoye
9803    Shchapovskoye
Name: DISTRICT, Length: 9804, dtype: object

In [19]:
district_names = district_prices['DISTRICT'].unique()
district_names.sort()
district_names

array(['Aeroport', 'Akademichesky', 'Alekseevsky', 'Altufyevsky', 'Arbat',
       'Babushkinsky', 'Basmanny', 'Begovoy', 'Beskudnikovsky',
       'Bibirevo', 'Biryulyovo Vostochnoye', 'Biryulyovo Zapadnoye',
       'Bogorodskoye', 'Brateyevo', 'Butyrsky', 'Chertanovo Severnoye',
       'Chertanovo Tsentralnoye', 'Chertanovo Yuzhnoye', 'Cheryomushki',
       'Danilovsky', 'Desyonovskoye', 'Dmitrovsky', 'Donskoy',
       'Dorogomilovo', 'Fili-Davydkovo', 'Filimonkovskoye',
       'Filyovsky Park', 'Gagarinsky', 'Golovinsky', 'Golyanovo',
       'Ivanovskoye', 'Izmaylovo', 'Khamovniki', 'Khoroshyovo-Mnyovniki',
       'Khoroshyovsky', 'Khovrino', 'Kievsky', 'Klyonovskoye',
       'Kokoshkino', 'Konkovo', 'Koptevo', 'Kosino-Ukhtomsky', 'Kotlovka',
       'Krasnopakhorskoye', 'Krasnoselsky', 'Krylatskoye', 'Kuntsevo',
       'Kurkino', 'Levoberezhny', 'Lianozovo', 'Lomonosovsky',
       'Losinoostrovsky', 'Marfino', 'Marushkinskoye', 'Maryina Roshcha',
       'Meshchansky', 'Metrogorodok', 'Mikhaylovo-Yartsevskoye', 'Mitino',
       'Molzhaninovsky', 'Moskovsky', 'Moskvorechye-Saburovo',
       'Mosrentgen', 'Mozhaysky', 'Nagatino-Sadovniki',
       'Nagatinsky Zaton', 'Nagorny', 'Novo-Peredelkino',
       'Novofyodorovskoye', 'Novogireyevo', 'Novokosino', 'Obruchevsky',
       'Ochakovo-Matveyevskoye', 'Orekhovo-Borisovo Severnoye',
       'Orekhovo-Borisovo Yuzhnoye', 'Ostankinsky', 'Otradnoye', 'Perovo',
       'Pervomayskoye', 'Pokrovskoye-Streshnevo', 'Preobrazhenskoye',
       'Presnensky', 'Prospekt Vernadskogo', 'Ramenki', 'Rogovskoye',
       'Rostokino', 'Ryazanovskoye', 'Savyolovsky', 'Severnoye Butovo',
       'Severnoye Izmaylovo', 'Severnoye Medvedkovo', 'Severnoye Tushino',
       'Severny', 'Shchapovskoye', 'Shcherbinka', 'Shchukino', 'Sokol',
       'Sokolinaya Gora', 'Sokolniki', 'Solntsevo', 'Sosenskoye',
       'Strogino', 'Sviblovo', 'Tagansky', 'Timiryazevsky', 'Troitsk',
       'Troparyovo-Nikulino', 'Tsaritsyno', 'Tverskoy', 'Tyoply Stan',
       'Veshnyaki', 'Vnukovo', 'Vnukovskoye', 'Voronovskoye',
       'Voskresenskoye', 'Vostochnoye Izmaylovo', 'Vostochny',
       'Voykovsky', 'Yakimanka', 'Yaroslavsky', 'Yasenevo',
       'Yuzhnoye Butovo', 'Yuzhnoye Medvedkovo', 'Yuzhnoye Tushino',
       'Zamoskvorechye', 'Zapadnoye Degunino', 'Zelenograd', 'Zyablikovo',
       'Zyuzino'], dtype=object)

In [21]:
# this column is not much inconsistant.
# we are replacing these letters bcz of pronunciation of Ё in Russian
district_prices['DISTRICT'] = district_prices['DISTRICT'].str.replace('oye', 'oe', case=False)
district_prices['DISTRICT'] = district_prices['DISTRICT'].str.replace('yovo', 'evo', case=False)
# replacing hyphens in between names to convert them in to standard form
district_prices['DISTRICT'] = district_prices['DISTRICT'].str.replace('-', ' ')
district_prices['DISTRICT'] = district_prices['DISTRICT'].str.capitalize()

In [23]:
# moving on to column 3
print(district_prices['OKRUG'])

0       CAO
1       CAO
2       CAO
3       CAO
4       CAO
       ...
9799    TAO
9800    TAO
9801    TAO
9802    TAO
9803    TAO
Name: OKRUG, Length: 9804, dtype: object

In [24]:
print(district_prices['OKRUG'].unique())

['CAO' 'SAO' 'SVAO' 'VAO' 'YuAO' 'YuZAO' 'ZAO' 'SZAO' 'ZelAO' 'NAO' 'TAO']

In the above cell you might see some lowercase letters and think they are inconsistent but they are not.This is how we write Russian in English

In [26]:
# moving to column 4
print(district_prices['SECONDARY PRICE PER SQM'])

0       480000
1       469100
2       502200
3       505100
4       523500
         ...
9799    112500
9800    116000
9801    117900
9802    119800
9803    121600
Name: SECONDARY PRICE PER SQM, Length: 9804, dtype: int64

In [34]:
district_prices['SECONDARY PRICE PER SQM'].describe()

count      9804.000000
mean     293669.543044
std      123593.449575
min       70600.000000
25%      220400.000000
50%      274200.000000
75%      344600.000000
max      812700.000000
Name: SECONDARY PRICE PER SQM, dtype: float64

In [29]:



































print(district_prices.isna().sum())

DATE                              0
DISTRICT                          0
OKRUG                             0
SECONDARY PRICE PER SQM           0
NEWBUILD PRICE PER SQM            0
RENTAL PRICE PER SQM MONTHLY      0
SECONDARY MOM CHANGE PCT        129
NEWBUILD MOM CHANGE PCT         129
N LISTINGS SECONDARY              0
N LISTINGS NEWBUILD               0
N LISTINGS RENTAL                 0
CBR KEY RATE PCT                  0
AVG MORTGAGE RATE PCT             0
dtype: int64

In [30]:
# moving to column 5
print(district_prices['NEWBUILD PRICE PER SQM'])

0       543700
1       531500
2       559800
3       541500
4       594800
         ...
9799    129800
9800    125200
9801    135800
9802    128500
9803    130900
Name: NEWBUILD PRICE PER SQM, Length: 9804, dtype: int64

In [31]:
district_prices['NEWBUILD PRICE PER SQM'].describe()

count      9804.000000
mean     323147.460220
std      136415.279338
min       74700.000000
25%      242375.000000
50%      301000.000000
75%      379000.000000
max      924900.000000
Name: NEWBUILD PRICE PER SQM, dtype: float64

In [35]:
# moving to column 6
print(district_prices['RENTAL PRICE PER SQM MONTHLY'])

0       2000
1       1955
2       2093
3       2104
4       2181
        ...
9799     469
9800     483
9801     491
9802     499
9803     507
Name: RENTAL PRICE PER SQM MONTHLY, Length: 9804, dtype: int64

In [36]:
district_prices['RENTAL PRICE PER SQM MONTHLY'].describe()

count    9804.000000
mean     1223.625051
std       514.966664
min       294.000000
25%       918.000000
50%      1142.500000
75%      1436.000000
max      3386.000000
Name: RENTAL PRICE PER SQM MONTHLY, dtype: float64

In [37]:
# moving to column 7
print(district_prices['SECONDARY MOM CHANGE PCT'])

0        NaN
1      -2.28
2       7.07
3       0.56
4       3.65
        ...
9799   -5.12
9800    3.12
9801    1.64
9802    1.67
9803    1.50
Name: SECONDARY MOM CHANGE PCT, Length: 9804, dtype: float64

In [39]:
district_prices['SECONDARY MOM CHANGE PCT'].describe()

count    9675.000000
mean        0.653792
std         3.693047
min       -13.090000
25%        -1.890000
50%         0.600000
75%         3.130000
max        15.740000
Name: SECONDARY MOM CHANGE PCT, dtype: float64

In [41]:
district_prices['SECONDARY MOM CHANGE PCT'].median()

0.6

In [44]:
district_prices['SECONDARY MOM CHANGE PCT'] = district_prices['SECONDARY MOM CHANGE PCT'].fillna(district_prices['SECONDARY MOM CHANGE PCT'].median())

In [45]:
print(district_prices['NEWBUILD MOM CHANGE PCT'])

0        NaN
1      -2.24
2       5.33
3      -3.27
4       9.84
        ...
9799   -2.16
9800   -3.56
9801    8.50
9802   -5.42
9803    1.90
Name: NEWBUILD MOM CHANGE PCT, Length: 9804, dtype: float64

In [46]:
district_prices['NEWBUILD MOM CHANGE PCT'].isnull().sum()

np.int64(129)

In [47]:
district_prices['NEWBUILD MOM CHANGE PCT'].describe()

count    9675.000000
mean        0.713295
std         5.149745
min       -15.630000
25%        -2.820000
50%         0.520000
75%         4.150000
max        25.910000
Name: NEWBUILD MOM CHANGE PCT, dtype: float64

In [48]:
district_prices['NEWBUILD MOM CHANGE PCT'] = district_prices['NEWBUILD MOM CHANGE PCT'].fillna(district_prices['NEWBUILD MOM CHANGE PCT'].median())

In [49]:
print(district_prices['N LISTINGS SECONDARY'])

0       104
1        22
2       104
3       168
4        66
       ...
9799     52
9800     37
9801     40
9802     35
9803    165
Name: N LISTINGS SECONDARY, Length: 9804, dtype: int64

In [51]:
district_prices['N LISTINGS SECONDARY'].describe()

count    9804.000000
mean      109.478070
std        52.000534
min        20.000000
25%        64.000000
50%       110.000000
75%       155.000000
max       199.000000
Name: N LISTINGS SECONDARY, dtype: float64

In [53]:
district_prices['N LISTINGS NEWBUILD'].describe()

count    9804.000000
mean       42.461444
std        21.655502
min         5.000000
25%        24.000000
50%        43.000000
75%        61.000000
max        79.000000
Name: N LISTINGS NEWBUILD, dtype: float64

In [54]:
district_prices['N LISTINGS RENTAL'].describe()

count    9804.000000
mean       64.638821
std        31.757889
min        10.000000
25%        38.000000
50%        65.000000
75%        92.000000
max       119.000000
Name: N LISTINGS RENTAL, dtype: float64

In [55]:
district_prices['CBR KEY RATE PCT']

0        6.00
1        6.00
2        6.00
3        4.25
4        4.25
        ...
9799    17.00
9800    17.00
9801    17.00
9802    17.00
9803    17.00
Name: CBR KEY RATE PCT, Length: 9804, dtype: float64

In [56]:
district_prices['AVG MORTGAGE RATE PCT']

0        8.50
1        8.50
2        8.50
3        6.75
4        6.75
        ...
9799    19.50
9800    19.50
9801    19.50
9802    19.50
9803    19.50
Name: AVG MORTGAGE RATE PCT, Length: 9804, dtype: float64

In [57]:
district_prices.head()

,DATE,DISTRICT,OKRUG,SECONDARY PRICE PER SQM,NEWBUILD PRICE PER SQM,RENTAL PRICE PER SQM MONTHLY,SECONDARY MOM CHANGE PCT,NEWBUILD MOM CHANGE PCT,N LISTINGS SECONDARY,N LISTINGS NEWBUILD,N LISTINGS RENTAL,CBR KEY RATE PCT,AVG MORTGAGE RATE PCT
0,2020-01-01,Arbat,CAO,480000,543700,2000,0.60,0.52,104,68,41,6.00,8.50
1,2020-02-01,Arbat,CAO,469100,531500,1955,-2.28,-2.24,22,63,50,6.00,8.50
2,2020-03-01,Arbat,CAO,502200,559800,2093,7.07,5.33,104,56,28,6.00,8.50
3,2020-04-01,Arbat,CAO,505100,541500,2104,0.56,-3.27,168,29,107,4.25,6.75
4,2020-05-01,Arbat,CAO,523500,594800,2181,3.65,9.84,66,58,57,4.25,6.75