In [64]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Fifa players.csv')
df.head()

/tmp/ipykernel_7530/724562228.py:4: DtypeWarning: Columns (104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/Fifa players.csv')

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,...,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,...,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,...,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,...,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,...,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png

In [66]:
# total numbers of columns
len(df.columns)

110

In [67]:
print(list(df.columns))

['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url']

In [68]:
# total numbers of rows
len(df)

16155

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
columns_to_include = [
    'short_name',
    'player_positions',
    'overall',
    'potential',
    'value_eur',
    'wage_eur',
    'age',
    'height_cm',
    'weight_kg',
    'club_name',
    'league_name',
    'league_level',
    'club_position',
    'nationality_name',
    'preferred_foot',
    'weak_foot',
    'skill_moves',
    'international_reputation',
    'work_rate',
    'body_type',
    'release_clause_eur',
    'pace',
    'shooting',
    'passing',
    'dribbling',
    'defending',
    'physic',
    'attacking_crossing',
    'attacking_finishing',
    'attacking_heading_accuracy',
    'attacking_short_passing',
    'attacking_volleys',
    'skill_dribbling',
    'skill_curve',
    'skill_fk_accuracy',
    'skill_long_passing',
    'skill_ball_control',
    'movement_acceleration',
    'movement_sprint_speed',
    'movement_agility',
    'movement_reactions',
    'movement_balance',
    'power_shot_power',
    'power_jumping',
    'power_stamina',
    'power_strength',
    'power_long_shots',
    'mentality_aggression',
    'mentality_interceptions',
    'mentality_positioning',
    'mentality_vision',
    'mentality_penalties',
    'mentality_composure',
    'defending_marking_awareness',
    'defending_standing_tackle',
    'defending_sliding_tackle'
]
columns_to_exclude = [
    'sofifa_id',
    'player_url',
    'long_name',
    'dob',
    'club_team_id',
    'club_jersey_number',
    'club_loaned_from',
    'club_joined',
    'club_contract_valid_until',
    'nationality_id',
    'nation_team_id',
    'nation_position',
    'nation_jersey_number',
    'real_face',
    'player_tags',
    'player_traits',
    'goalkeeping_diving',
    'goalkeeping_handling',
    'goalkeeping_kicking',
    'goalkeeping_positioning',
    'goalkeeping_reflexes',
    'goalkeeping_speed',
    'ls',
    'st',
    'rs',
    'lw',
    'lf',
    'cf',
    'rf',
    'rw',
    'lam',
    'cam',
    'ram',
    'lm',
    'lcm',
    'cm',
    'rcm',
    'rm',
    'lwb',
    'ldm',
    'cdm',
    'rdm',
    'rwb',
    'lb',
    'lcb',
    'cb',
    'rcb',
    'rb',
    'gk',
    'player_face_url',
    'club_logo_url',
    'club_flag_url',
    'nation_logo_url',
    'nation_flag_url'
]
df = df.drop(columns=columns_to_exclude)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16155 entries, 0 to 16154
Data columns (total 56 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   short_name                   16155 non-null  object
 1   player_positions             16155 non-null  object
 2   overall                      16155 non-null  int64
 3   potential                    16155 non-null  int64
 4   value_eur                    15844 non-null  float64
 5   wage_eur                     15916 non-null  float64
 6   age                          16155 non-null  int64
 7   height_cm                    16155 non-null  int64
 8   weight_kg                    16155 non-null  int64
 9   club_name                    15916 non-null  object
 10  league_name                  15916 non-null  object
 11  league_level                 15916 non-null  float64
 12  club_position                15916 non-null  object
 13  nationality_name             16155 non-null  object
 14  preferred_foot               16155 non-null  object
 15  weak_foot                    16155 non-null  int64
 16  skill_moves                  16155 non-null  int64
 17  international_reputation     16155 non-null  int64
 18  work_rate                    16155 non-null  object
 19  body_type                    16155 non-null  object
 20  release_clause_eur           0 non-null      float64
 21  pace                         14380 non-null  float64
 22  shooting                     14380 non-null  float64
 23  passing                      14380 non-null  float64
 24  dribbling                    14380 non-null  float64
 25  defending                    14380 non-null  float64
 26  physic                       14380 non-null  float64
 27  attacking_crossing           16155 non-null  int64
 28  attacking_finishing          16155 non-null  int64
 29  attacking_heading_accuracy   16155 non-null  int64
 30  attacking_short_passing      16155 non-null  int64
 31  attacking_volleys            16155 non-null  int64
 32  skill_dribbling              16155 non-null  int64
 33  skill_curve                  16155 non-null  int64
 34  skill_fk_accuracy            16155 non-null  int64
 35  skill_long_passing           16155 non-null  int64
 36  skill_ball_control           16155 non-null  int64
 37  movement_acceleration        16155 non-null  int64
 38  movement_sprint_speed        16155 non-null  int64
 39  movement_agility             16155 non-null  int64
 40  movement_reactions           16155 non-null  int64
 41  movement_balance             16155 non-null  int64
 42  power_shot_power             16155 non-null  int64
 43  power_jumping                16155 non-null  int64
 44  power_stamina                16155 non-null  int64
 45  power_strength               16155 non-null  int64
 46  power_long_shots             16155 non-null  int64
 47  mentality_aggression         16155 non-null  int64
 48  mentality_interceptions      16155 non-null  int64
 49  mentality_positioning        16155 non-null  int64
 50  mentality_vision             16155 non-null  int64
 51  mentality_penalties          16155 non-null  int64
 52  mentality_composure          0 non-null      float64
 53  defending_marking_awareness  16155 non-null  int64
 54  defending_standing_tackle    16155 non-null  int64
 55  defending_sliding_tackle     16155 non-null  int64
dtypes: float64(11), int64(36), object(9)
memory usage: 6.9+ MB

In [72]:
df = df.drop(columns= 'mentality_composure')

In [73]:
df.describe()

,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,league_level,weak_foot,skill_moves,...,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle
count,16155.000000,16155.000000,1.584400e+04,15916.000000,16155.000000,16155.000000,16155.000000,15916.000000,16155.000000,16155.000000,...,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000
mean,63.830393,68.350108,1.081706e+06,13252.513194,24.776230,181.083627,75.474342,1.378424,2.929619,2.265429,...,65.095574,48.329124,55.395543,46.879418,50.113278,50.765645,49.648344,45.009037,47.656639,45.885918
std,7.169896,6.580610,2.842704e+06,23608.922510,4.625321,6.618974,6.891796,0.736796,0.650281,0.717399,...,12.616545,16.585339,16.814330,18.278554,16.395071,15.098199,14.552244,17.915206,18.743105,18.145497
min,40.000000,40.000000,1.000000e+03,2000.000000,16.000000,155.000000,50.000000,1.000000,1.000000,1.000000,...,21.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
25%,59.000000,64.000000,1.300000e+05,2000.000000,21.000000,176.000000,70.000000,1.000000,3.000000,2.000000,...,58.000000,33.000000,43.000000,25.000000,37.000000,41.000000,39.000000,25.000000,25.000000,25.000000
50%,64.000000,68.000000,3.500000e+05,5000.000000,24.000000,181.000000,75.000000,1.000000,3.000000,2.000000,...,66.000000,51.000000,58.000000,50.000000,53.000000,52.000000,50.000000,46.000000,52.000000,49.000000
75%,68.000000,73.000000,8.250000e+05,10000.000000,28.000000,186.000000,80.000000,2.000000,3.000000,3.000000,...,74.000000,62.000000,68.000000,63.000000,63.000000,62.000000,61.000000,61.000000,64.000000,62.000000
max,93.000000,95.000000,1.005000e+08,550000.000000,44.000000,204.000000,110.000000,4.000000,5.000000,5.000000,...,97.000000,93.000000,95.000000,93.000000,94.000000,96.000000,95.000000,90.000000,91.000000,95.000000

In [74]:
df.isnull().sum()

short_name                         0
player_positions                   0
overall                            0
potential                          0
value_eur                        311
wage_eur                         239
age                                0
height_cm                          0
weight_kg                          0
club_name                        239
league_name                      239
league_level                     239
club_position                    239
nationality_name                   0
preferred_foot                     0
weak_foot                          0
skill_moves                        0
international_reputation           0
work_rate                          0
body_type                          0
release_clause_eur             16155
pace                            1775
shooting                        1775
passing                         1775
dribbling                       1775
defending                       1775
physic                          1775
attacking_crossing                 0
attacking_finishing                0
attacking_heading_accuracy         0
attacking_short_passing            0
attacking_volleys                  0
skill_dribbling                    0
skill_curve                        0
skill_fk_accuracy                  0
skill_long_passing                 0
skill_ball_control                 0
movement_acceleration              0
movement_sprint_speed              0
movement_agility                   0
movement_reactions                 0
movement_balance                   0
power_shot_power                   0
power_jumping                      0
power_stamina                      0
power_strength                     0
power_long_shots                   0
mentality_aggression               0
mentality_interceptions            0
mentality_positioning              0
mentality_vision                   0
mentality_penalties                0
defending_marking_awareness        0
defending_standing_tackle          0
defending_sliding_tackle           0
dtype: int64

In [75]:
# filling missing value
financials = ['value_eur', 'wage_eur', 'release_clause_eur']
df[financials] = df[financials].fillna(0)

In [76]:
df[financials].isnull().sum()

value_eur             0
wage_eur              0
release_clause_eur    0
dtype: int64

In [77]:
club = ['club_name', 'league_name', 'club_position']
df[club] = df[club].fillna('Unknown')

In [78]:
df[club].isnull().sum()

club_name        0
league_name      0
club_position    0
dtype: int64

In [79]:
performance_Attributes = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']
df[performance_Attributes] = df[performance_Attributes].fillna(df[performance_Attributes].median())

In [80]:
df[performance_Attributes].isnull().sum()

pace         0
shooting     0
passing      0
dribbling    0
defending    0
physic       0
dtype: int64

In [82]:
df['league_level'] = df['league_level'].fillna(1.0)

In [83]:
df.isnull().sum()

short_name                     0
player_positions               0
overall                        0
potential                      0
value_eur                      0
wage_eur                       0
age                            0
height_cm                      0
weight_kg                      0
club_name                      0
league_name                    0
league_level                   0
club_position                  0
nationality_name               0
preferred_foot                 0
weak_foot                      0
skill_moves                    0
international_reputation       0
work_rate                      0
body_type                      0
release_clause_eur             0
pace                           0
shooting                       0
passing                        0
dribbling                      0
defending                      0
physic                         0
attacking_crossing             0
attacking_finishing            0
attacking_heading_accuracy     0
attacking_short_passing        0
attacking_volleys              0
skill_dribbling                0
skill_curve                    0
skill_fk_accuracy              0
skill_long_passing             0
skill_ball_control             0
movement_acceleration          0
movement_sprint_speed          0
movement_agility               0
movement_reactions             0
movement_balance               0
power_shot_power               0
power_jumping                  0
power_stamina                  0
power_strength                 0
power_long_shots               0
mentality_aggression           0
mentality_interceptions        0
mentality_positioning          0
mentality_vision               0
mentality_penalties            0
defending_marking_awareness    0
defending_standing_tackle      0
defending_sliding_tackle       0
dtype: int64

In [84]:
# fixing dtypes
cols_to_fix = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'league_level']

df[cols_to_fix] = df[cols_to_fix].astype('int64')

In [86]:
# Returns a Series with column names and their unique value counts
df.nunique()

short_name                     15204
player_positions                 907
overall                           53
potential                         49
value_eur                        161
wage_eur                          41
age                               29
height_cm                         48
weight_kg                         54
club_name                        578
league_name                       38
league_level                       4
club_position                     30
nationality_name                 149
preferred_foot                     2
weak_foot                          5
skill_moves                        5
international_reputation           5
work_rate                          9
body_type                         10
release_clause_eur                 1
pace                              74
shooting                          70
passing                           67
dribbling                         67
defending                         69
physic                            63
attacking_crossing                72
attacking_finishing               74
attacking_heading_accuracy        75
attacking_short_passing           75
attacking_volleys                 72
skill_dribbling                   75
skill_curve                       74
skill_fk_accuracy                 72
skill_long_passing                74
skill_ball_control                76
movement_acceleration             78
movement_sprint_speed             78
movement_agility                  77
movement_reactions                70
movement_balance                  78
power_shot_power                  76
power_jumping                     74
power_stamina                     76
power_strength                    76
power_long_shots                  72
mentality_aggression              76
mentality_interceptions           74
mentality_positioning             74
mentality_vision                  75
mentality_penalties               75
defending_marking_awareness       71
defending_standing_tackle         72
defending_sliding_tackle          72
dtype: int64

In [92]:
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16155 entries, 0 to 16154
Data columns (total 55 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   short_name                   16155 non-null  object
 1   player_positions             16155 non-null  object
 2   overall                      16155 non-null  int64
 3   potential                    16155 non-null  int64
 4   value_eur                    16155 non-null  float64
 5   wage_eur                     16155 non-null  float64
 6   age                          16155 non-null  int64
 7   height_cm                    16155 non-null  int64
 8   weight_kg                    16155 non-null  int64
 9   club_name                    16155 non-null  object
 10  league_name                  16155 non-null  object
 11  league_level                 16155 non-null  int64
 12  club_position                16155 non-null  object
 13  nationality_name             16155 non-null  object
 14  preferred_foot               16155 non-null  object
 15  weak_foot                    16155 non-null  int64
 16  skill_moves                  16155 non-null  int64
 17  international_reputation     16155 non-null  int64
 18  work_rate                    16155 non-null  object
 19  body_type                    16155 non-null  object
 20  release_clause_eur           16155 non-null  float64
 21  pace                         16155 non-null  int64
 22  shooting                     16155 non-null  int64
 23  passing                      16155 non-null  int64
 24  dribbling                    16155 non-null  int64
 25  defending                    16155 non-null  int64
 26  physic                       16155 non-null  int64
 27  attacking_crossing           16155 non-null  int64
 28  attacking_finishing          16155 non-null  int64
 29  attacking_heading_accuracy   16155 non-null  int64
 30  attacking_short_passing      16155 non-null  int64
 31  attacking_volleys            16155 non-null  int64
 32  skill_dribbling              16155 non-null  int64
 33  skill_curve                  16155 non-null  int64
 34  skill_fk_accuracy            16155 non-null  int64
 35  skill_long_passing           16155 non-null  int64
 36  skill_ball_control           16155 non-null  int64
 37  movement_acceleration        16155 non-null  int64
 38  movement_sprint_speed        16155 non-null  int64
 39  movement_agility             16155 non-null  int64
 40  movement_reactions           16155 non-null  int64
 41  movement_balance             16155 non-null  int64
 42  power_shot_power             16155 non-null  int64
 43  power_jumping                16155 non-null  int64
 44  power_stamina                16155 non-null  int64
 45  power_strength               16155 non-null  int64
 46  power_long_shots             16155 non-null  int64
 47  mentality_aggression         16155 non-null  int64
 48  mentality_interceptions      16155 non-null  int64
 49  mentality_positioning        16155 non-null  int64
 50  mentality_vision             16155 non-null  int64
 51  mentality_penalties          16155 non-null  int64
 52  defending_marking_awareness  16155 non-null  int64
 53  defending_standing_tackle    16155 non-null  int64
 54  defending_sliding_tackle     16155 non-null  int64
dtypes: float64(3), int64(43), object(9)
memory usage: 6.8+ MB

In [94]:
df.describe()

,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,league_level,weak_foot,skill_moves,...,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle
count,16155.000000,16155.000000,1.615500e+04,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,...,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000
mean,63.830393,68.350108,1.060882e+06,13056.453110,24.776230,181.083627,75.474342,1.372826,2.929619,2.265429,...,65.095574,48.329124,55.395543,46.879418,50.113278,50.765645,49.648344,45.009037,47.656639,45.885918
std,7.169896,6.580610,2.819128e+06,23488.182571,4.625321,6.618974,6.891796,0.732751,0.650281,0.717399,...,12.616545,16.585339,16.814330,18.278554,16.395071,15.098199,14.552244,17.915206,18.743105,18.145497
min,40.000000,40.000000,0.000000e+00,0.000000,16.000000,155.000000,50.000000,1.000000,1.000000,1.000000,...,21.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
25%,59.000000,64.000000,1.200000e+05,2000.000000,21.000000,176.000000,70.000000,1.000000,3.000000,2.000000,...,58.000000,33.000000,43.000000,25.000000,37.000000,41.000000,39.000000,25.000000,25.000000,25.000000
50%,64.000000,68.000000,3.500000e+05,5000.000000,24.000000,181.000000,75.000000,1.000000,3.000000,2.000000,...,66.000000,51.000000,58.000000,50.000000,53.000000,52.000000,50.000000,46.000000,52.000000,49.000000
75%,68.000000,73.000000,8.250000e+05,10000.000000,28.000000,186.000000,80.000000,2.000000,3.000000,3.000000,...,74.000000,62.000000,68.000000,63.000000,63.000000,62.000000,61.000000,61.000000,64.000000,62.000000
max,93.000000,95.000000,1.005000e+08,550000.000000,44.000000,204.000000,110.000000,4.000000,5.000000,5.000000,...,97.000000,93.000000,95.000000,93.000000,94.000000,96.000000,95.000000,90.000000,91.000000,95.000000

In [96]:
df.isnull().sum()

short_name                     0
player_positions               0
overall                        0
potential                      0
value_eur                      0
wage_eur                       0
age                            0
height_cm                      0
weight_kg                      0
club_name                      0
league_name                    0
league_level                   0
club_position                  0
nationality_name               0
preferred_foot                 0
weak_foot                      0
skill_moves                    0
international_reputation       0
work_rate                      0
body_type                      0
release_clause_eur             0
pace                           0
shooting                       0
passing                        0
dribbling                      0
defending                      0
physic                         0
attacking_crossing             0
attacking_finishing            0
attacking_heading_accuracy     0
attacking_short_passing        0
attacking_volleys              0
skill_dribbling                0
skill_curve                    0
skill_fk_accuracy              0
skill_long_passing             0
skill_ball_control             0
movement_acceleration          0
movement_sprint_speed          0
movement_agility               0
movement_reactions             0
movement_balance               0
power_shot_power               0
power_jumping                  0
power_stamina                  0
power_strength                 0
power_long_shots               0
mentality_aggression           0
mentality_interceptions        0
mentality_positioning          0
mentality_vision               0
mentality_penalties            0
defending_marking_awareness    0
defending_standing_tackle      0
defending_sliding_tackle       0
dtype: int64

In [97]:
df.to_csv('/content/Fifa players.csv')